# ERD commands (generated by the erd plugin) — keep at the repo root and run from the root
# If you already have a Makefile, just add one line to it: `include erd.mk`
#
#   make erd               : generate docs + lint for every ERD unit (folders with erd.env)
#   make erd P=apps/api    : one unit only
#   make erd-check [P=..]  : check docs are up to date (CI; fails on drift)
#   make erd-sql   [P=..]  : DBML → SQL only
#   make erd-list          : list ERD units
#   make erd-view  [P=..]  : view docs in the terminal (glow)
#   make erd-check-changed [BASE=origin/main] : check only units whose schema changed vs the base branch (PRs, CI)
# Existing DB server: make erd PG=postgres://user:pass@localhost:5432  (MySQL: MY=mysql://...)
# Message language: ERD_LANG (ko|en) from the first unit's erd.env; override with make ... ERD_LANG=en

ERD_SCRIPT := scripts/erd-doc.sh
ERD_UNITS = $(if $(P),$(P),$(patsubst %/erd.env,%,$(shell find . -name erd.env -not -path '*/node_modules/*' -not -path '*/.git/*' -not -path '*/vendor/*' -not -path '*/.venv/*' | sort)))

ERD_LANG ?= $(shell grep -hs '^ERD_LANG=' $(firstword $(ERD_UNITS))/erd.env | head -1 | cut -d= -f2 | tr -d "'\" ")
export ERD_LANG

.PHONY: erd erd-check erd-check-changed erd-sql erd-list erd-view

erd:
	@set -e; for u in $(ERD_UNITS); do PG=$(PG) MY=$(MY) $(ERD_SCRIPT) doc $$u; echo; done

erd-check:
	@rc=0; for u in $(ERD_UNITS); do PG=$(PG) MY=$(MY) $(ERD_SCRIPT) check $$u || rc=1; echo; done; exit $$rc

# Units with schema-related changes = committed since base + uncommitted + new files (scripts/erd-changed.sh)
erd-check-changed:
	@units="$$(scripts/erd-changed.sh --names $(if $(BASE),--base $(BASE)))" || exit $$?; \
	if [ -z "$$units" ]; then echo "$(if $(filter ko,$(ERD_LANG)),스키마가 바뀐 ERD 단위 없음,No ERD unit with schema changes)"; exit 0; fi; \
	rc=0; for u in $$units; do PG=$(PG) MY=$(MY) $(ERD_SCRIPT) check $$u || rc=1; echo; done; exit $$rc

erd-sql:
	@set -e; for u in $(ERD_UNITS); do $(ERD_SCRIPT) sql $$u; done

erd-list:
	@for u in $(ERD_UNITS); do printf '%-30s %s\n' "$$u" "$$(grep -hE '^ERD_(DIALECT|SOURCE)=' $$u/erd.env | tr '\n' ' ')"; done

erd-view:
	@glow -p $(firstword $(ERD_UNITS))/docs/schema/README.md
